@TMS.AuthService_HostAddress = https://localhost:8020/api/auth
@TokenAccess = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbjEyM0BtYWlsLmJveCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzYzNTY3MzgxLCJpc3MiOiJhdXRoLXNlcnZpY2UiLCJhdWQiOiJUTVMifQ.7CEldpMBon3k-q5sovRJAy7tF78LAA21nATsWzNjmeA

### Migrate
GET {{TMS.AuthService_HostAddress}}/migrate
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TokenAccess}}

### Register admin
POST {{TMS.AuthService_HostAddress}}/register
Content-Type: application/json
Accept: application/json

{
    "username": "AdminName",
    "email": "AdminEmail",
    "password": "AdminPassword",
    "role": 1
}

### Register user
POST {{TMS.AuthService_HostAddress}}/register
Content-Type: application/json
Accept: application/json

{
    "username": "UserName",
    "email": "UserEmail",
    "password": "UserPassword",
    "role": 0
}


### Login Admin
POST {{TMS.AuthService_HostAddress}}/login
Content-Type: application/json
Accept: application/json

{
    "username": "AdminName",
    "password": "AdminPassword"
}

### Login User
POST {{TMS.AuthService_HostAddress}}/login
Content-Type: application/json
Accept: application/json

{
    "username": "UserName",
    "password": "UserPassword"
}

### GET USERS
GET {{TMS.AuthService_HostAddress}}/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TokenAccess}}


### GET REFRESH TOKEN
POST {{TMS.AuthService_HostAddress}}/refresh
Content-Type: application/json
Accept: application/json

{
  "refresh-token": "l7H1i1GOj4T3KfwJ+xo7x2B9vKQc4/+dKrD29bmHGmCPZPv05XYSIt58KuiSYOnR+sHOjatL1o2RNbIsCk7KOg=="
}


###