@TMS.TaskService_HostAddress = https://localhost:11964/api/tasks
@user_id = 1
@project_id = 1
@task_id = 3

### Greeting
GET {{TMS.TaskService_HostAddress}}/greeting
Content-Type: application/json
Accept: application/json


### CreateTask
POST {{TMS.TaskService_HostAddress}}
Content-Type: application/json
Accept: application/json

{
  "Title" : "Task #10",
  "Description" : "",
  "Deadline" : "2025-11-06T20:09:53+03:00",
  "Status" : 0,
  "Priority" : 0,
  "ProjectId" : {{project_id}},
  "AssigneeId" : {{user_id}}
}

### GetTasks
GET {{TMS.TaskService_HostAddress}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVXNlck5hbWUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJFbWFpbCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE3NjI1MzEzNDgsImlzcyI6ImF1dGgtc2VydmljZSIsImF1ZCI6IlRNUyJ9.8u-xkXTFYJf2tBJ7onj3Ks9qPXNY2DoQZQH6XHGmlIE

### GetTask
GET {{TMS.TaskService_HostAddress}}/{{task_id}}
Content-Type: application/json
Accept: application/json

### UpdateTask
PUT {{TMS.TaskService_HostAddress}}/{{task_id}}
Content-Type: application/json
Accept: application/json

{
  "Title": "New Task #11",
  "Description": "New Description",
  "Deadline" : "2025-11-08T20:09:53+03:00",
  "Status": 1,
  "Priority": 1,
  "AssigneeId": {{user_id}}
}

### DeleteTask
DELETE {{TMS.TaskService_HostAddress}}/{{task_id}}
Content-Type: application/json
Accept: application/json

###
