@TMS.TaskService_HostAddress = https://localhost:6233/api
@user_id = 1
@task_id = 2
@comment_id = 4
@attachment_id = 1

#### Create
POST {{TMS.TaskService_HostAddress}}/tasks/{{task_id}}/attachments?fileName=example.txt
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVXNlck5hbWUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJVc2VyRW1haWwiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiZXhwIjoxNzYyOTAzMzYxLCJpc3MiOiJhdXRoLXNlcnZpY2UiLCJhdWQiOiJUTVMifQ._9YKmEWtlQ5dQqSJ0SWToAmtpKCODBUgYlADDXcUGnU
Content-Type: multipart/form-data; boundary="--------------------------abc123def456"

----------------------------abc123def456
Content-Disposition: form-data; name="file"; filename="example.txt"
Content-Type: text/plain

<содержимое файла example.txt>
----------------------------abc123def456--

#### Get
GET {{TMS.TaskService_HostAddress}}/attachments/{{attachment_id}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVXNlck5hbWUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJVc2VyRW1haWwiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiZXhwIjoxNzYyOTAzMzYxLCJpc3MiOiJhdXRoLXNlcnZpY2UiLCJhdWQiOiJUTVMifQ._9YKmEWtlQ5dQqSJ0SWToAmtpKCODBUgYlADDXcUGnU


#### GetByTaskId
GET {{TMS.TaskService_HostAddress}}/tasks/{{task_id}}/attachments
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVXNlck5hbWUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJVc2VyRW1haWwiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiZXhwIjoxNzYyOTAzMzYxLCJpc3MiOiJhdXRoLXNlcnZpY2UiLCJhdWQiOiJUTVMifQ._9YKmEWtlQ5dQqSJ0SWToAmtpKCODBUgYlADDXcUGnU


#### GetFileById
GET {{TMS.TaskService_HostAddress}}/files?name=example.txt&path=tasks%2F2%2Fattachments%2F03ec4eee-2b5f-418e-9001-46c57832006d
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVXNlck5hbWUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJVc2VyRW1haWwiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiZXhwIjoxNzYyOTAzMzYxLCJpc3MiOiJhdXRoLXNlcnZpY2UiLCJhdWQiOiJUTVMifQ._9YKmEWtlQ5dQqSJ0SWToAmtpKCODBUgYlADDXcUGnU


####