@TMS.TaskService_HostAddress = https://localhost:13563/api/tasks
@user_id = 1
@project_id = 1
@task_id = 3

### Greeting
GET {{TMS.TaskService_HostAddress}}/greeting
Content-Type: application/json
Accept: application/json


### CreateTask
POST {{TMS.TaskService_HostAddress}}
Content-Type: application/json
Accept: application/json

{
  "Title" : "Task #10",
  "Description" : "",
  "Deadline" : "2025-11-06T20:09:53+03:00",
  "Status" : 0,
  "Priority" : 0,
  "ProjectId" : {{project_id}},
  "AssigneeId" : {{user_id}}
}

### GetTasks
GET {{TMS.TaskService_HostAddress}}
Content-Type: application/json
Accept: application/json

### GetTask
GET {{TMS.TaskService_HostAddress}}/{{task_id}}
Content-Type: application/json
Accept: application/json

### UpdateTask
PUT {{TMS.TaskService_HostAddress}}/{{task_id}}
Content-Type: application/json
Accept: application/json

{
  "Title": "New Task #11",
  "Description": "New Description",
  "Deadline" : "2025-11-08T20:09:53+03:00",
  "Status": 1,
  "Priority": 1,
  "AssigneeId": {{user_id}}
}

### DeleteTask
DELETE {{TMS.TaskService_HostAddress}}/{{task_id}}
Content-Type: application/json
Accept: application/json

###
