@TMS.TaskService_HostAddress = https://localhost:8227/api/projects
@user_id = 1
@new_project_id = 1

### CreateProject
POST {{TMS.TaskService_HostAddress}}
Content-Type: application/json
Accept: application/json

{
  "Name" : "Project #1",
  "Description" : "",
  "Status" : 0,
  "UserId" : {{user_id}}
}

### GetProjects
GET {{TMS.TaskService_HostAddress}}
Content-Type: application/json
Accept: application/json

### GetProject
GET {{TMS.TaskService_HostAddress}}/{{new_project_id}}
Content-Type: application/json
Accept: application/json

### UpdateProject
PUT {{TMS.TaskService_HostAddress}}/{{new_project_id}}
Content-Type: application/json
Accept: application/json

{
  "Name": "New Project #1",
  "Description": "New Description",
  "Status": 2
}

### DeleteProject
DELETE {{TMS.TaskService_HostAddress}}/{{new_project_id}}
Content-Type: application/json
Accept: application/json

###
